const CART_KEY="gp_store_cart_v1",CUSTOMER_KEY="gp_customer_details_v1",money=n=>`₹${Math.round(n).toLocaleString("en-IN")}`;
const couriers={surface:[["Trackon",100],["Shree Maruti",100],["Speed Post",150],["Delhivery",300],["BlueDart",300],["Ecom Express",300]],air:[["Trackon Air",150],["Shree Maruti Air",150]],prime:[["Trackon Prime",200]]};
let pincodeData={},cart={};try{cart=JSON.parse(localStorage.getItem(CART_KEY)||"{}")}catch{}
const entries=()=>Object.entries(cart).map(([id,qty])=>[GP_PRODUCTS.find(p=>p.id===id),qty]).filter(x=>x[0]);
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));render()}
function qty(id,d){cart[id]=Math.max(0,(cart[id]||0)+d);if(!cart[id])delete cart[id];saveCart()}
function selectedDelivery(){return document.querySelector('input[name="delivery"]:checked')?.value||"surface"}
function refreshCouriers(){const type=selectedDelivery(),sel=document.getElementById("courier");sel.innerHTML=couriers[type].map(([n,r])=>`<option value="${r}">${n} — ${money(r)}/kg</option>`).join("");calculate()}
function calculate(){const list=entries(),total=list.reduce((n,[p,q])=>n+p.price*q,0),grams=list.reduce((n,[p,q])=>n+p.weight*q,0),kg=Math.max(1,Math.ceil(grams/1000)),rate=Number(document.getElementById("courier").value||100),charge=kg*rate;document.getElementById("productTotal").textContent=money(total);document.getElementById("weight").textContent=`${kg} kg`;document.getElementById("deliveryCharge").textContent=money(charge);document.getElementById("grandTotal").textContent=money(total+charge);return{list,total,grams,kg,rate,charge,grand:total+charge}}
function render(){const list=entries(),count=list.reduce((n,[,q])=>n+q,0),battery=list.some(([p])=>p.battery);document.querySelectorAll("[data-cart-count]").forEach(x=>x.textContent=count);document.getElementById("batteryNote").hidden=!battery;document.querySelectorAll("[data-fast]").forEach(x=>x.hidden=battery);if(battery&&selectedDelivery()!=="surface")document.querySelector('input[value="surface"]').checked=true;document.getElementById("checkoutItems").innerHTML=list.length?list.map(([p,q])=>`<div class="mini"><img src="images/${p.image}" alt=""><div><b>${p.name}</b><div class="qty" style="margin-top:6px"><button data-minus="${p.id}">−</button><span>${q}</span><button data-plus="${p.id}">+</button></div></div><strong>${money(p.price*q)}</strong></div>`).join(""):`<div class="empty"><p>Your cart is empty.</p><a class="back" href="index.html">Return to store</a></div>`;document.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>qty(b.dataset.minus,-1));document.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>qty(b.dataset.plus,1));refreshCouriers()}
function customer(){return["name","mobile","alt","email","house","landmark","address","pincode","state","city","postoffice"].reduce((o,id)=>(o[id]=document.getElementById(id).value.trim(),o),{})}
function validateCustomer(){const form=document.getElementById("checkoutForm");if(!form.reportValidity())return false;const c=customer();if(!/^[6-9]\d{9}$/.test(c.mobile)){alert("Please enter a valid 10-digit mobile number.");return false}localStorage.setItem(CUSTOMER_KEY,JSON.stringify(c));return true}
function orderText(){const c=customer(),x=calculate();return `*Games Planet Order*\n\n${x.list.map(([p,q])=>`• ${p.name} × ${q} = ${money(p.price*q)}`).join("\n")}\n\nProducts: ${money(x.total)}\nDelivery: ${money(x.charge)}\n*Total: ${money(x.grand)}*\n\nName: ${c.name}\nMobile: ${c.mobile}${c.alt?`\nAlternate: ${c.alt}`:""}\nAddress: ${c.house}, ${c.address}${c.landmark?`, ${c.landmark}`:""}, ${c.city}, ${c.state} - ${c.pincode}${c.postoffice?`\nPost Office: ${c.postoffice}`:""}\nDelivery: ${selectedDelivery()} / ${document.getElementById("courier").selectedOptions[0]?.textContent||""}`;}
document.querySelectorAll('input[name="delivery"]').forEach(r=>r.onchange=refreshCouriers);document.getElementById("courier").onchange=calculate;
document.getElementById("upiBtn").onclick=()=>{if(!entries().length)return alert("Your cart is empty.");if(!validateCustomer())return;const x=calculate();location.href=`upi://pay?pa=7983624797@ybl&pn=Games%20Planet&am=${x.grand}&cu=INR&tn=Games%20Planet%20Order`};
document.getElementById("whatsappBtn").onclick=()=>{if(!entries().length)return alert("Your cart is empty.");if(!validateCustomer())return;window.open(`https://wa.me/917983624797?text=${encodeURIComponent(orderText())}`,"_blank")};
try{const c=JSON.parse(localStorage.getItem(CUSTOMER_KEY)||"{}");Object.entries(c).forEach(([k,v])=>{const e=document.getElementById(k);if(e)e.value=v})}catch{}
fetch("pincode_data.json").then(r=>r.json()).then(d=>pincodeData=d).catch(()=>{});
document.getElementById("pincode").addEventListener("input",e=>{if(e.target.value.length!==6)return;const row=pincodeData[e.target.value];if(!row)return;document.getElementById("state").value=row.state||row.State||"";document.getElementById("city").value=row.district||row.city||row.District||"";const offices=row.postoffices||row.post_offices||row.offices||[];document.getElementById("postoffice").innerHTML=`<option value="">Select Post Office</option>${offices.map(o=>`<option>${typeof o==="string"?o:o.name||o.office||""}</option>`).join("")}`});
render();
